<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SistemaVentas.Common\SistemaVentas.Common.csproj" />
    <ProjectReference Include="..\SistemaVentas.Business\SistemaVentas.Business.csproj" />
    <ProjectReference Include="..\SistemaVentas.Data\SistemaVentas.Data.csproj" />
  </ItemGroup>
</Project>
